apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myApp
spec:
  destination:
    name: ''
    namespace: myApp
    server: 'https://kubernetes.default.svc'
  source:
    path: Manifest
    repoURL: 'https://github.com/RajithRajan/ArgoCD-trial.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2