apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-devops
spec:
  selector:
    matchLabels:
      app: devops-sample-app
      tier: database
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-sample-app
        tier: database
        track: stable
    spec:
      containers:
        - name: devops-db 
          image: "mongo"
          ports:
            - name: db
              containerPort: 27017