apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: devops-sample-app
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-sample-app
        tier: frontend
        track: stable
    spec:
      containers:
        - name: angular
          image: "rajithr007/devops-sample-app-ui:latest"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]