apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: devops-sample-app
    tier: backend
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: LoadBalancer