apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: devops-sample-app
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 81
    targetPort: 80
  type: LoadBalancer